// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/rates/rates.proto

package rates

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlertCondition int32

const (
	AlertCondition_ALERT_CONDITION_UNSPECIFIED AlertCondition = 0
	AlertCondition_ALERT_CONDITION_ABOVE       AlertCondition = 1
	AlertCondition_ALERT_CONDITION_BELOW       AlertCondition = 2
)

// Enum value maps for AlertCondition.
var (
	AlertCondition_name = map[int32]string{
		0: "ALERT_CONDITION_UNSPECIFIED",
		1: "ALERT_CONDITION_ABOVE",
		2: "ALERT_CONDITION_BELOW",
	}
	AlertCondition_value = map[string]int32{
		"ALERT_CONDITION_UNSPECIFIED": 0,
		"ALERT_CONDITION_ABOVE":       1,
		"ALERT_CONDITION_BELOW":       2,
	}
)

func (x AlertCondition) Enum() *AlertCondition {
	p := new(AlertCondition)
	*p = x
	return p
}

func (x AlertCondition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertCondition) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rates_rates_proto_enumTypes[0].Descriptor()
}

func (AlertCondition) Type() protoreflect.EnumType {
	return &file_proto_rates_rates_proto_enumTypes[0]
}

func (x AlertCondition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertCondition.Descriptor instead.
func (AlertCondition) EnumDescriptor() ([]byte, []int) {
	return file_proto_rates_rates_proto_rawDescGZIP(), []int{0}
}

// CurrencyPair описывает пару базовой и квотируемой валюты, например BASE=BTC, QUOTE=USD.
type CurrencyPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          string                 `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Quote         string                 `protobuf:"bytes,2,opt,name=quote,proto3" json:"quote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrencyPair) Reset() {
	*x = CurrencyPair{}
	mi := &file_proto_rates_rates_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrencyPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyPair) ProtoMessage() {}

func (x *CurrencyPair) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rates_rates_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyPair.ProtoReflect.Descriptor instead.
func (*CurrencyPair) Descriptor() ([]byte, []int) {
	return file_proto_rates_rates_proto_rawDescGZIP(), []int{0}
}

func (x *CurrencyPair) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *CurrencyPair) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

type GetRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          *CurrencyPair          `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRateRequest) Reset() {
	*x = GetRateRequest{}
	mi := &file_proto_rates_rates_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateRequest) ProtoMessage() {}

func (x *GetRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rates_rates_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateRequest.ProtoReflect.Descriptor instead.
func (*GetRateRequest) Descriptor() ([]byte, []int) {
	return file_proto_rates_rates_proto_rawDescGZIP(), []int{1}
}

func (x *GetRateRequest) GetPair() *CurrencyPair {
	if x != nil {
		return x.Pair
	}
	return nil
}

type RateResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Pair      *CurrencyPair          `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Price     float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Источник данных: "cache" или "external_api" — удобно для дебага/метрик.
	Source        string `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateResponse) Reset() {
	*x = RateResponse{}
	mi := &file_proto_rates_rates_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateResponse) ProtoMessage() {}

func (x *RateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rates_rates_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateResponse.ProtoReflect.Descriptor instead.
func (*RateResponse) Descriptor() ([]byte, []int) {
	return file_proto_rates_rates_proto_rawDescGZIP(), []int{2}
}

func (x *RateResponse) GetPair() *CurrencyPair {
	if x != nil {
		return x.Pair
	}
	return nil
}

func (x *RateResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *RateResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *RateResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ListRatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pairs         []*CurrencyPair        `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRatesRequest) Reset() {
	*x = ListRatesRequest{}
	mi := &file_proto_rates_rates_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRatesRequest) ProtoMessage() {}

func (x *ListRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rates_rates_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRatesRequest.ProtoReflect.Descriptor instead.
func (*ListRatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_rates_rates_proto_rawDescGZIP(), []int{3}
}

func (x *ListRatesRequest) GetPairs() []*CurrencyPair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

type ListRatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rates         []*RateResponse        `protobuf:"bytes,1,rep,name=rates,proto3" json:"rates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRatesResponse) Reset() {
	*x = ListRatesResponse{}
	mi := &file_proto_rates_rates_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRatesResponse) ProtoMessage() {}

func (x *ListRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rates_rates_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRatesResponse.ProtoReflect.Descriptor instead.
func (*ListRatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_rates_rates_proto_rawDescGZIP(), []int{4}
}

func (x *ListRatesResponse) GetRates() []*RateResponse {
	if x != nil {
		return x.Rates
	}
	return nil
}

type SubscribeRatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          *CurrencyPair          `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRatesRequest) Reset() {
	*x = SubscribeRatesRequest{}
	mi := &file_proto_rates_rates_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRatesRequest) ProtoMessage() {}

func (x *SubscribeRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rates_rates_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRatesRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_rates_rates_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeRatesRequest) GetPair() *CurrencyPair {
	if x != nil {
		return x.Pair
	}
	return nil
}

type RateUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          *CurrencyPair          `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	OldPrice      float64                `protobuf:"fixed64,2,opt,name=old_price,json=oldPrice,proto3" json:"old_price,omitempty"`
	NewPrice      float64                `protobuf:"fixed64,3,opt,name=new_price,json=newPrice,proto3" json:"new_price,omitempty"`
	ChangePercent float64                `protobuf:"fixed64,4,opt,name=change_percent,json=changePercent,proto3" json:"change_percent,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateUpdate) Reset() {
	*x = RateUpdate{}
	mi := &file_proto_rates_rates_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateUpdate) ProtoMessage() {}

func (x *RateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rates_rates_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateUpdate.ProtoReflect.Descriptor instead.
func (*RateUpdate) Descriptor() ([]byte, []int) {
	return file_proto_rates_rates_proto_rawDescGZIP(), []int{6}
}

func (x *RateUpdate) GetPair() *CurrencyPair {
	if x != nil {
		return x.Pair
	}
	return nil
}

func (x *RateUpdate) GetOldPrice() float64 {
	if x != nil {
		return x.OldPrice
	}
	return 0
}

func (x *RateUpdate) GetNewPrice() float64 {
	if x != nil {
		return x.NewPrice
	}
	return 0
}

func (x *RateUpdate) GetChangePercent() float64 {
	if x != nil {
		return x.ChangePercent
	}
	return 0
}

func (x *RateUpdate) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pair          *CurrencyPair          `protobuf:"bytes,2,opt,name=pair,proto3" json:"pair,omitempty"`
	Condition     AlertCondition         `protobuf:"varint,3,opt,name=condition,proto3,enum=rates.AlertCondition" json:"condition,omitempty"`
	Threshold     float64                `protobuf:"fixed64,4,opt,name=threshold,proto3" json:"threshold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlertRequest) Reset() {
	*x = CreateAlertRequest{}
	mi := &file_proto_rates_rates_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlertRequest) ProtoMessage() {}

func (x *CreateAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rates_rates_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlertRequest.ProtoReflect.Descriptor instead.
func (*CreateAlertRequest) Descriptor() ([]byte, []int) {
	return file_proto_rates_rates_proto_rawDescGZIP(), []int{7}
}

func (x *CreateAlertRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAlertRequest) GetPair() *CurrencyPair {
	if x != nil {
		return x.Pair
	}
	return nil
}

func (x *CreateAlertRequest) GetCondition() AlertCondition {
	if x != nil {
		return x.Condition
	}
	return AlertCondition_ALERT_CONDITION_UNSPECIFIED
}

func (x *CreateAlertRequest) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

type CreateAlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertId       string                 `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlertResponse) Reset() {
	*x = CreateAlertResponse{}
	mi := &file_proto_rates_rates_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlertResponse) ProtoMessage() {}

func (x *CreateAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rates_rates_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlertResponse.ProtoReflect.Descriptor instead.
func (*CreateAlertResponse) Descriptor() ([]byte, []int) {
	return file_proto_rates_rates_proto_rawDescGZIP(), []int{8}
}

func (x *CreateAlertResponse) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

type SubscribeAlertsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeAlertsRequest) Reset() {
	*x = SubscribeAlertsRequest{}
	mi := &file_proto_rates_rates_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeAlertsRequest) ProtoMessage() {}

func (x *SubscribeAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rates_rates_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeAlertsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeAlertsRequest) Descriptor() ([]byte, []int) {
	return file_proto_rates_rates_proto_rawDescGZIP(), []int{9}
}

func (x *SubscribeAlertsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AlertTriggered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertId       string                 `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	Pair          *CurrencyPair          `protobuf:"bytes,2,opt,name=pair,proto3" json:"pair,omitempty"`
	Condition     AlertCondition         `protobuf:"varint,3,opt,name=condition,proto3,enum=rates.AlertCondition" json:"condition,omitempty"`
	Threshold     float64                `protobuf:"fixed64,4,opt,name=threshold,proto3" json:"threshold,omitempty"`
	CurrentPrice  float64                `protobuf:"fixed64,5,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	TriggeredAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=triggered_at,json=triggeredAt,proto3" json:"triggered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertTriggered) Reset() {
	*x = AlertTriggered{}
	mi := &file_proto_rates_rates_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertTriggered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertTriggered) ProtoMessage() {}

func (x *AlertTriggered) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rates_rates_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertTriggered.ProtoReflect.Descriptor instead.
func (*AlertTriggered) Descriptor() ([]byte, []int) {
	return file_proto_rates_rates_proto_rawDescGZIP(), []int{10}
}

func (x *AlertTriggered) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *AlertTriggered) GetPair() *CurrencyPair {
	if x != nil {
		return x.Pair
	}
	return nil
}

func (x *AlertTriggered) GetCondition() AlertCondition {
	if x != nil {
		return x.Condition
	}
	return AlertCondition_ALERT_CONDITION_UNSPECIFIED
}

func (x *AlertTriggered) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *AlertTriggered) GetCurrentPrice() float64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *AlertTriggered) GetTriggeredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TriggeredAt
	}
	return nil
}

var File_proto_rates_rates_proto protoreflect.FileDescriptor

const file_proto_rates_rates_proto_rawDesc = "" +
	"\n" +
	"\x17proto/rates/rates.proto\x12\x05rates\x1a\x1fgoogle/protobuf/timestamp.proto\"8\n" +
	"\fCurrencyPair\x12\x12\n" +
	"\x04base\x18\x01 \x01(\tR\x04base\x12\x14\n" +
	"\x05quote\x18\x02 \x01(\tR\x05quote\"9\n" +
	"\x0eGetRateRequest\x12'\n" +
	"\x04pair\x18\x01 \x01(\v2\x13.rates.CurrencyPairR\x04pair\"\xa0\x01\n" +
	"\fRateResponse\x12'\n" +
	"\x04pair\x18\x01 \x01(\v2\x13.rates.CurrencyPairR\x04pair\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"=\n" +
	"\x10ListRatesRequest\x12)\n" +
	"\x05pairs\x18\x01 \x03(\v2\x13.rates.CurrencyPairR\x05pairs\">\n" +
	"\x11ListRatesResponse\x12)\n" +
	"\x05rates\x18\x01 \x03(\v2\x13.rates.RateResponseR\x05rates\"@\n" +
	"\x15SubscribeRatesRequest\x12'\n" +
	"\x04pair\x18\x01 \x01(\v2\x13.rates.CurrencyPairR\x04pair\"\xd1\x01\n" +
	"\n" +
	"RateUpdate\x12'\n" +
	"\x04pair\x18\x01 \x01(\v2\x13.rates.CurrencyPairR\x04pair\x12\x1b\n" +
	"\told_price\x18\x02 \x01(\x01R\boldPrice\x12\x1b\n" +
	"\tnew_price\x18\x03 \x01(\x01R\bnewPrice\x12%\n" +
	"\x0echange_percent\x18\x04 \x01(\x01R\rchangePercent\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa9\x01\n" +
	"\x12CreateAlertRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x04pair\x18\x02 \x01(\v2\x13.rates.CurrencyPairR\x04pair\x123\n" +
	"\tcondition\x18\x03 \x01(\x0e2\x15.rates.AlertConditionR\tcondition\x12\x1c\n" +
	"\tthreshold\x18\x04 \x01(\x01R\tthreshold\"0\n" +
	"\x13CreateAlertResponse\x12\x19\n" +
	"\balert_id\x18\x01 \x01(\tR\aalertId\"1\n" +
	"\x16SubscribeAlertsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x8b\x02\n" +
	"\x0eAlertTriggered\x12\x19\n" +
	"\balert_id\x18\x01 \x01(\tR\aalertId\x12'\n" +
	"\x04pair\x18\x02 \x01(\v2\x13.rates.CurrencyPairR\x04pair\x123\n" +
	"\tcondition\x18\x03 \x01(\x0e2\x15.rates.AlertConditionR\tcondition\x12\x1c\n" +
	"\tthreshold\x18\x04 \x01(\x01R\tthreshold\x12#\n" +
	"\rcurrent_price\x18\x05 \x01(\x01R\fcurrentPrice\x12=\n" +
	"\ftriggered_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vtriggeredAt*g\n" +
	"\x0eAlertCondition\x12\x1f\n" +
	"\x1bALERT_CONDITION_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ALERT_CONDITION_ABOVE\x10\x01\x12\x19\n" +
	"\x15ALERT_CONDITION_BELOW\x10\x022\xdb\x02\n" +
	"\fRatesService\x125\n" +
	"\aGetRate\x12\x15.rates.GetRateRequest\x1a\x13.rates.RateResponse\x12>\n" +
	"\tListRates\x12\x17.rates.ListRatesRequest\x1a\x18.rates.ListRatesResponse\x12C\n" +
	"\x0eSubscribeRates\x12\x1c.rates.SubscribeRatesRequest\x1a\x11.rates.RateUpdate0\x01\x12D\n" +
	"\vCreateAlert\x12\x19.rates.CreateAlertRequest\x1a\x1a.rates.CreateAlertResponse\x12I\n" +
	"\x0fSubscribeAlerts\x12\x1d.rates.SubscribeAlertsRequest\x1a\x15.rates.AlertTriggered0\x01B/Z-github.com/Cryezidl/cryptotracker/proto/ratesb\x06proto3"

var (
	file_proto_rates_rates_proto_rawDescOnce sync.Once
	file_proto_rates_rates_proto_rawDescData []byte
)

func file_proto_rates_rates_proto_rawDescGZIP() []byte {
	file_proto_rates_rates_proto_rawDescOnce.Do(func() {
		file_proto_rates_rates_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rates_rates_proto_rawDesc), len(file_proto_rates_rates_proto_rawDesc)))
	})
	return file_proto_rates_rates_proto_rawDescData
}

var file_proto_rates_rates_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_rates_rates_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_rates_rates_proto_goTypes = []any{
	(AlertCondition)(0),            // 0: rates.AlertCondition
	(*CurrencyPair)(nil),           // 1: rates.CurrencyPair
	(*GetRateRequest)(nil),         // 2: rates.GetRateRequest
	(*RateResponse)(nil),           // 3: rates.RateResponse
	(*ListRatesRequest)(nil),       // 4: rates.ListRatesRequest
	(*ListRatesResponse)(nil),      // 5: rates.ListRatesResponse
	(*SubscribeRatesRequest)(nil),  // 6: rates.SubscribeRatesRequest
	(*RateUpdate)(nil),             // 7: rates.RateUpdate
	(*CreateAlertRequest)(nil),     // 8: rates.CreateAlertRequest
	(*CreateAlertResponse)(nil),    // 9: rates.CreateAlertResponse
	(*SubscribeAlertsRequest)(nil), // 10: rates.SubscribeAlertsRequest
	(*AlertTriggered)(nil),         // 11: rates.AlertTriggered
	(*timestamppb.Timestamp)(nil),  // 12: google.protobuf.Timestamp
}
var file_proto_rates_rates_proto_depIdxs = []int32{
	1,  // 0: rates.GetRateRequest.pair:type_name -> rates.CurrencyPair
	1,  // 1: rates.RateResponse.pair:type_name -> rates.CurrencyPair
	12, // 2: rates.RateResponse.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 3: rates.ListRatesRequest.pairs:type_name -> rates.CurrencyPair
	3,  // 4: rates.ListRatesResponse.rates:type_name -> rates.RateResponse
	1,  // 5: rates.SubscribeRatesRequest.pair:type_name -> rates.CurrencyPair
	1,  // 6: rates.RateUpdate.pair:type_name -> rates.CurrencyPair
	12, // 7: rates.RateUpdate.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 8: rates.CreateAlertRequest.pair:type_name -> rates.CurrencyPair
	0,  // 9: rates.CreateAlertRequest.condition:type_name -> rates.AlertCondition
	1,  // 10: rates.AlertTriggered.pair:type_name -> rates.CurrencyPair
	0,  // 11: rates.AlertTriggered.condition:type_name -> rates.AlertCondition
	12, // 12: rates.AlertTriggered.triggered_at:type_name -> google.protobuf.Timestamp
	2,  // 13: rates.RatesService.GetRate:input_type -> rates.GetRateRequest
	4,  // 14: rates.RatesService.ListRates:input_type -> rates.ListRatesRequest
	6,  // 15: rates.RatesService.SubscribeRates:input_type -> rates.SubscribeRatesRequest
	8,  // 16: rates.RatesService.CreateAlert:input_type -> rates.CreateAlertRequest
	10, // 17: rates.RatesService.SubscribeAlerts:input_type -> rates.SubscribeAlertsRequest
	3,  // 18: rates.RatesService.GetRate:output_type -> rates.RateResponse
	5,  // 19: rates.RatesService.ListRates:output_type -> rates.ListRatesResponse
	7,  // 20: rates.RatesService.SubscribeRates:output_type -> rates.RateUpdate
	9,  // 21: rates.RatesService.CreateAlert:output_type -> rates.CreateAlertResponse
	11, // 22: rates.RatesService.SubscribeAlerts:output_type -> rates.AlertTriggered
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_rates_rates_proto_init() }
func file_proto_rates_rates_proto_init() {
	if File_proto_rates_rates_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rates_rates_proto_rawDesc), len(file_proto_rates_rates_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rates_rates_proto_goTypes,
		DependencyIndexes: file_proto_rates_rates_proto_depIdxs,
		EnumInfos:         file_proto_rates_rates_proto_enumTypes,
		MessageInfos:      file_proto_rates_rates_proto_msgTypes,
	}.Build()
	File_proto_rates_rates_proto = out.File
	file_proto_rates_rates_proto_goTypes = nil
	file_proto_rates_rates_proto_depIdxs = nil
}
