// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/rates/rates.proto

package rates

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RatesService_GetRate_FullMethodName         = "/rates.RatesService/GetRate"
	RatesService_ListRates_FullMethodName       = "/rates.RatesService/ListRates"
	RatesService_SubscribeRates_FullMethodName  = "/rates.RatesService/SubscribeRates"
	RatesService_CreateAlert_FullMethodName     = "/rates.RatesService/CreateAlert"
	RatesService_SubscribeAlerts_FullMethodName = "/rates.RatesService/SubscribeAlerts"
)

// RatesServiceClient is the client API for RatesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RatesService отдаёт текущий курс валюты и позволяет подписаться на изменения.
type RatesServiceClient interface {
	// GetRate возвращает текущий курс по запрошенной паре (например BTC/USD).
	// Сервис сначала смотрит в кеш (Redis), и только при промахе идёт во внешний API.
	GetRate(ctx context.Context, in *GetRateRequest, opts ...grpc.CallOption) (*RateResponse, error)
	// ListRates возвращает курсы сразу по нескольким парам за один запрос.
	ListRates(ctx context.Context, in *ListRatesRequest, opts ...grpc.CallOption) (*ListRatesResponse, error)
	// SubscribeRates открывает server-стрим: клиент получает обновление каждый раз,
	// когда курс запрошенной пары меняется (приходит из Redis pub/sub внутри сервера).
	SubscribeRates(ctx context.Context, in *SubscribeRatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RateUpdate], error)
	// CreateAlert создаёт пороговое уведомление: "сообщи мне, когда курс пересечёт X".
	CreateAlert(ctx context.Context, in *CreateAlertRequest, opts ...grpc.CallOption) (*CreateAlertResponse, error)
	// SubscribeAlerts стримит сработавшие алерты конкретного пользователя.
	SubscribeAlerts(ctx context.Context, in *SubscribeAlertsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AlertTriggered], error)
}

type ratesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRatesServiceClient(cc grpc.ClientConnInterface) RatesServiceClient {
	return &ratesServiceClient{cc}
}

func (c *ratesServiceClient) GetRate(ctx context.Context, in *GetRateRequest, opts ...grpc.CallOption) (*RateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RateResponse)
	err := c.cc.Invoke(ctx, RatesService_GetRate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratesServiceClient) ListRates(ctx context.Context, in *ListRatesRequest, opts ...grpc.CallOption) (*ListRatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRatesResponse)
	err := c.cc.Invoke(ctx, RatesService_ListRates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratesServiceClient) SubscribeRates(ctx context.Context, in *SubscribeRatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RateUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RatesService_ServiceDesc.Streams[0], RatesService_SubscribeRates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRatesRequest, RateUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RatesService_SubscribeRatesClient = grpc.ServerStreamingClient[RateUpdate]

func (c *ratesServiceClient) CreateAlert(ctx context.Context, in *CreateAlertRequest, opts ...grpc.CallOption) (*CreateAlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAlertResponse)
	err := c.cc.Invoke(ctx, RatesService_CreateAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratesServiceClient) SubscribeAlerts(ctx context.Context, in *SubscribeAlertsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AlertTriggered], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RatesService_ServiceDesc.Streams[1], RatesService_SubscribeAlerts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeAlertsRequest, AlertTriggered]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RatesService_SubscribeAlertsClient = grpc.ServerStreamingClient[AlertTriggered]

// RatesServiceServer is the server API for RatesService service.
// All implementations must embed UnimplementedRatesServiceServer
// for forward compatibility.
//
// RatesService отдаёт текущий курс валюты и позволяет подписаться на изменения.
type RatesServiceServer interface {
	// GetRate возвращает текущий курс по запрошенной паре (например BTC/USD).
	// Сервис сначала смотрит в кеш (Redis), и только при промахе идёт во внешний API.
	GetRate(context.Context, *GetRateRequest) (*RateResponse, error)
	// ListRates возвращает курсы сразу по нескольким парам за один запрос.
	ListRates(context.Context, *ListRatesRequest) (*ListRatesResponse, error)
	// SubscribeRates открывает server-стрим: клиент получает обновление каждый раз,
	// когда курс запрошенной пары меняется (приходит из Redis pub/sub внутри сервера).
	SubscribeRates(*SubscribeRatesRequest, grpc.ServerStreamingServer[RateUpdate]) error
	// CreateAlert создаёт пороговое уведомление: "сообщи мне, когда курс пересечёт X".
	CreateAlert(context.Context, *CreateAlertRequest) (*CreateAlertResponse, error)
	// SubscribeAlerts стримит сработавшие алерты конкретного пользователя.
	SubscribeAlerts(*SubscribeAlertsRequest, grpc.ServerStreamingServer[AlertTriggered]) error
	mustEmbedUnimplementedRatesServiceServer()
}

// UnimplementedRatesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRatesServiceServer struct{}

func (UnimplementedRatesServiceServer) GetRate(context.Context, *GetRateRequest) (*RateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRate not implemented")
}
func (UnimplementedRatesServiceServer) ListRates(context.Context, *ListRatesRequest) (*ListRatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRates not implemented")
}
func (UnimplementedRatesServiceServer) SubscribeRates(*SubscribeRatesRequest, grpc.ServerStreamingServer[RateUpdate]) error {
	return status.Error(codes.Unimplemented, "method SubscribeRates not implemented")
}
func (UnimplementedRatesServiceServer) CreateAlert(context.Context, *CreateAlertRequest) (*CreateAlertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAlert not implemented")
}
func (UnimplementedRatesServiceServer) SubscribeAlerts(*SubscribeAlertsRequest, grpc.ServerStreamingServer[AlertTriggered]) error {
	return status.Error(codes.Unimplemented, "method SubscribeAlerts not implemented")
}
func (UnimplementedRatesServiceServer) mustEmbedUnimplementedRatesServiceServer() {}
func (UnimplementedRatesServiceServer) testEmbeddedByValue()                      {}

// UnsafeRatesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RatesServiceServer will
// result in compilation errors.
type UnsafeRatesServiceServer interface {
	mustEmbedUnimplementedRatesServiceServer()
}

func RegisterRatesServiceServer(s grpc.ServiceRegistrar, srv RatesServiceServer) {
	// If the following call panics, it indicates UnimplementedRatesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RatesService_ServiceDesc, srv)
}

func _RatesService_GetRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatesServiceServer).GetRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatesService_GetRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatesServiceServer).GetRate(ctx, req.(*GetRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatesService_ListRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatesServiceServer).ListRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatesService_ListRates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatesServiceServer).ListRates(ctx, req.(*ListRatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatesService_SubscribeRates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RatesServiceServer).SubscribeRates(m, &grpc.GenericServerStream[SubscribeRatesRequest, RateUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RatesService_SubscribeRatesServer = grpc.ServerStreamingServer[RateUpdate]

func _RatesService_CreateAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatesServiceServer).CreateAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatesService_CreateAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatesServiceServer).CreateAlert(ctx, req.(*CreateAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatesService_SubscribeAlerts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeAlertsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RatesServiceServer).SubscribeAlerts(m, &grpc.GenericServerStream[SubscribeAlertsRequest, AlertTriggered]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RatesService_SubscribeAlertsServer = grpc.ServerStreamingServer[AlertTriggered]

// RatesService_ServiceDesc is the grpc.ServiceDesc for RatesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RatesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rates.RatesService",
	HandlerType: (*RatesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRate",
			Handler:    _RatesService_GetRate_Handler,
		},
		{
			MethodName: "ListRates",
			Handler:    _RatesService_ListRates_Handler,
		},
		{
			MethodName: "CreateAlert",
			Handler:    _RatesService_CreateAlert_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeRates",
			Handler:       _RatesService_SubscribeRates_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeAlerts",
			Handler:       _RatesService_SubscribeAlerts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/rates/rates.proto",
}
